### ISSUE TITLE
Subfolders having same name as a module will cause that module to build

### ISSUE THREAD

**Issue by tjokimie** [circle-makotom-orbs/config-splitting#4]
## Description of the issue

I have a project with the following directory structure

```
.
├── .circleci
│   ├── modules.txt
│   ├── ...
├── bar
│   ├── .circleci
│   ├── ...
├── foo
│   ├── .circleci
│   ├── bar
└── ...
```

and `modules.txt` having the following modules defined

```
foo
bar
```

If I make edits in `foo/bar` folder I see two builds running instead of one as the build for the `bar` module will get triggered too.

## Steps to reproduce the issue

This PR demonstrates the issue: https://github.com/tjokimie/config-splitting-bug/pull/2

## What did I expect?

I expect only the module folder where I am making edits to build, e.g. like here: https://github.com/tjokimie/config-splitting-bug/pull/1

**Comment by tjokimie** [comment]
Moved to correct repository: https://github.com/circle-makotom-orbs/config-splitting/issues/4

**Comment by tjokimie** [comment]
@makotom Any thoughts on this one?

**Comment by makotom** [comment]
@tjokimie Good catch - I just filed #5!

**Comment by makotom** [comment]
Closing the issue in favour of #5 being merged.
